version: "3"
services:
  hon:
    image: superbjorn09/kongor:latest
    container_name: kongor_online
    volumes:
      - hondata_logs:/root/Heroes of Newerth x64/game
      - hondata_proxy:/app/drive_c/users/root/AppData/Roaming/HonProxyManager
    restart: unless-stopped
    ports:
      - "${port_proxy_start}-${port_proxy_end}:${port_proxy_start}-${port_proxy_end}/udp"
    environment:
      - commands=${commands}
      - metricbeat=${use_metricbeat}
      - ping_port=${port_proxy_start}
      - proxyconf=count=${count}\nip=${ip}\nstartport=${startport}\nstartvoicePort=${startvoiceport}\nregion=${proxy_region}
      - _name=${server_name}
      - _region=${region}
      - _user=${username}
      - _servers_per_core=${servers_per_core}
      - _affinity=${servers_per_core}
      - _admin=${username}
      - _hf_cert_chain=/etc/monitoring/certs/honfigurator-chain.pem
      - _hf_client_pem=/etc/monitoring/certs/filebeat.pem
      - _hf_client_key=/etc/monitoring/certs/filebeat.key
      - _game_log_path=/root/Heroes\ of\ Newerth\ x64/game/logs/*clog
    networks:
      - kongor_online_network

volumes:
  hondata_logs:
  hondata_proxy:

networks:
  kongor_online_network:
    driver_opts:
      com.docker.network.driver.mtu: 1450
